---
- name: Rails server | copy config
  template: 'src=rails_server.service.j2 dest=/etc/systemd/system/rails_server.service owner=root group=root mode=0644'
  tags: [conf]
  notify:
    - restart rails server
